name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: install trunk
      run: cargo install --locked trunk
    - name: install dep
      run : cargo install tauri-cli
    - name: Build
      run: cargo tauri build
    - name: Run tests
      run: cargo test --verbose
