name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Cache Crates
      uses: actions/cache@v4.0.2
      with:
          path: |
            ./target
            ~/.cargo            
          key: debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            debug-${{ runner.os }}-${{ hashFiles('rust-toolchain.toml') }}-
            debug-${{ runner.os }}-         
    - uses: actions/checkout@v4
    - name: install trunk
      run: cargo install --locked trunk
    - name: install dep
      run : cargo install tauri-cli
    - name: Build
      run: cargo tauri build
    - name: Run tests
      run: cargo test --verbose
